### ISSUE TITLE
plot the script through gnuplot

### ISSUE THREAD

**Issue by kookma** [mammothb/vscode-gnuplot#2] opened 2018-02-11 18:12 UTC
Is there any capability to load or send the script file to gnuplot?
I mean the feature to run the script file from VS code.

**Comment by mammothb** [comment] 2018-02-12 05:21
Sorry, there are no plans for that feature for now since this extension was intended to be a simple syntax highlighter only.

If you want to run gnuplot scripts using VS code, I recommend using the [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner) extension and adding a custom entry to ```code-runner.executorMap``` such as ```"gnuplot": "gnuplot $filename"``` to run the gnuplot script. Hope that helps.

**Comment by kookma** [comment] 2018-02-12 12:45
Many thanks!
By the way, the list of keywords, autocomplete seems incomplete!
For example "set xlabel ...

**Comment by mammothb** [comment] 2018-02-12 12:50
I'll look into adding more snippets. I'll close this for now and leave the other one open

**Closed as completed by mammothb** 2018-02-12 12:50 UTC
